[book]
authors = ["Henning Nolzen"]
language = "en"
multilingual = false
src = "src"
title = "sywi"

[output.html]
git-repository-url = "https://github.com/hnolzen/sywi"
edit-url-template = "https://github.com/hnolzen/fsywi/edit/main/{path}"

[output.html.search]
limit-results = 15
teaser-word-count = 50
use-boolean-and = true

[preprocessor.toc]
command = "mdbook-toc"
marker = "[[_TOC_]]"
max-level = 2
renderer = ["html"]